[package]
name = "vor-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
vor-core = { path = "../vor-core" }
vor-protocol = { path = "../vor-protocol" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
