[package]
name = "vor-approver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
prost.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
vor-approval = { path = "../../crates/vor-approval" }
vor-protocol = { path = "../../crates/vor-protocol" }
vor-secrets = { path = "../../crates/vor-secrets" }
vor-wire = { path = "../../crates/vor-wire" }
windows.workspace = true
