[package]
name = "vor-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
rand.workspace = true
thiserror.workspace = true
windows-sys.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true